import { Router } from 'express';
import accountRoutes from './accountRoutes.js';
import adminRoutes from './adminRoutes.js';
import authRoutes from './authRoutes.js';
import beneficiaryRoutes from './beneficiaryRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import healthRoutes from './healthRoutes.js';
import loanRoutes from './loanRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import operationsRoutes from './operationsRoutes.js';
import transactionRoutes from './transactionRoutes.js';
import transferRoutes from './transferRoutes.js';

const router = Router();
router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/admin', adminRoutes);
router.use('/notifications', notificationRoutes);
router.use('/accounts', accountRoutes);
router.use('/transactions', transactionRoutes);
router.use('/transfers', transferRoutes);
router.use('/beneficiaries', beneficiaryRoutes);
router.use('/loans', loanRoutes);
router.use('/dashboards', dashboardRoutes);
router.use('/operations', operationsRoutes);
export default router;
