import { Router } from 'express';
import accountRoutes from './accountRoutes.js';
import authRoutes from './authRoutes.js';
import beneficiaryRoutes from './beneficiaryRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import familyRoutes from './familyRoutes.js';
import healthRoutes from './healthRoutes.js';
import loanRoutes from './loanRoutes.js';
import juniorBankingRoutes from './juniorBankingRoutes.js';
import operationsRoutes from './operationsRoutes.js';
import transactionRoutes from './transactionRoutes.js';
import transferRoutes from './transferRoutes.js';
import securityRoutes from './securityRoutes.js';

const router = Router();
router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/accounts', accountRoutes);
router.use('/transactions', transactionRoutes);
router.use('/transfers', transferRoutes);
router.use('/beneficiaries', beneficiaryRoutes);
router.use('/loans', loanRoutes);
router.use('/dashboards', dashboardRoutes);
router.use('/families', familyRoutes);
router.use('/junior-banking', juniorBankingRoutes);
router.use('/operations', operationsRoutes);
router.use('/security', securityRoutes);
export default router;
